### ISSUE TITLE
Fuente listas de nombres

### ISSUE THREAD

**Issue by dersteppenwolf** [ucd-dnp/ConTexto#1]
Buen día, 
Es posible conocer cual es la fuente original de los archivos de nombres clasificados por género?

https://github.com/ucd-dnp/ConTexto/blob/master/contexto/data/listas_stopwords/nombres_mujeres.txt
https://github.com/ucd-dnp/ConTexto/blob/master/contexto/data/listas_stopwords/nombres_hombres.txt

Gracias.

**Comment by baldesco** [comment]
Hola Juan Carlos,

La principal fuente para obtener los nombres por género fue esta:

https://script.byu.edu/Plugins/FileManager/Files/Images/SiteAssets/Spanish-Nombres.pdf

Luego complementamos algunos nombres desde otras fuentes, pero este enlace fue el insumo principal.

Saludos!
