### ISSUE TITLE
Añadir opciones de personalización para nubes de palabras

### ISSUE THREAD

**Issue by ucd-dnp** [ucd-dnp/ConTexto#4]
Las siguientes acciones van encaminadas a dar más posibilidades para personalizar la estética de una nube de palabras.

- [x] Modificar función `nube_palabras` para permitir hacer nubes en diferentes formas, poder cambiar el color de fondo y poder dibujar el contorno de la forma de la nube, configurando el color y grosor de dicho contorno.

- [x] Hacer las modificaciones necesarias a la documentación de la función `nube_palabras` para que tenga en cuenta las adiciones realizadas al código.

- [x] Incluir ejemplo de uso de las nuevas características en los cuadernos de Jupyter y la página de documentación.

**Comment by baldesco** [comment]
Ya quedó la función modificada, junto con la documentación y ejemplo actualizados. Se puede ver en el commit 52bc481351ddba9249ef15d66e2fc3f9b429a1e3.
