### ISSUE TITLE
Implementar *lexical dispersion plot* en ConTexto

### ISSUE THREAD

**Issue by ucd-dnp** [ucd-dnp/ConTexto#5]
Añadir al módulo `exploracion` de ConTexto una función que permita realizar la gráfica conocida como *lexical dispersion plot*. La función debe permitir generar esta gráfica para un texto de entrada, y tener parámetros que permitan personalizar aspectos de la figura resultante.

**Comment by davidinsuasty** [comment]
Se agrega grafica_dispersion al módulo de exploración
